{% set name = "django-grappelli" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 90f53247d51a588a0553563fd85b6620b6b30c4f7969860ec325bfb97c2609df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - django

test:
  imports:
    - grappelli
    - grappelli.templatetags
    - grappelli.views
    - grappelli.dashboard
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://django-grappelli.readthedocs.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A jazzy skin for the Django Admin-Interface

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
