{% set name = "django-grappelli" %}
{% set version = "3.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-grappelli-{{ version }}.tar.gz
  sha256: 0bfa9f7ec424f30c33dc7f18d9a1604ad09ac1e9143e0386849a81d1fd2af0ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django

test:
  imports:
    - grappelli
    - grappelli.templatetags
    - grappelli.views
    - grappelli.dashboard
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://django-grappelli.readthedocs.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A jazzy skin for the Django Admin-Interface

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
